config/routes.rb
Rails.application.routes.draw do

  api_version(:module => "V1", :header => {:name => "Accept", :value => "application/vnd.mycompany.com; version=1"}, :parameter => {:name => "version", :value => "1"}, :path => {:value => "v1"}) do
    resources :api, :except => [:show]
  end
  root 'access#index'

  resources :game_session_players
  resources :player_awards
  resources :awards
  resources :player_histories
  resources :game_sessions
  resources :players
  resources :games

  match ':controller(/:action(/:id))', :via => [:get, :post]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/game_session.rb
class GameSession < ApplicationRecord

  has_many :game_session_players, :dependent => :delete_all

  belongs_to :game

end

app/controllers/game_sessions_controller.rb
class GameSessionsController < ApplicationController
  before_action :set_game_session, only: [:show, :edit, :update, :destroy]

  # GET /game_sessions
  # GET /game_sessions.json
  def index
    @game_sessions = GameSession.all
  end

  # GET /game_sessions/1
  # GET /game_sessions/1.json
  def show
  end

  # GET /game_sessions/new
  def new
    @game_session = GameSession.new
  end

  # GET /game_sessions/1/edit
  def edit
  end

  # POST /game_sessions
  # POST /game_sessions.json
  def create
    @game_session = GameSession.new(game_session_params)

    respond_to do |format|
      if @game_session.save
        format.html { redirect_to @game_session, notice: 'Game session was successfully created.' }
        format.json { render :show, status: :created, location: @game_session }
      else
        format.html { render :new }
        format.json { render json: @game_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /game_sessions/1
  # PATCH/PUT /game_sessions/1.json
  def update
    respond_to do |format|
      if @game_session.update(game_session_params)
        format.html { redirect_to @game_session, notice: 'Game session was successfully updated.' }
        format.json { render :show, status: :ok, location: @game_session }
      else
        format.html { render :edit }
        format.json { render json: @game_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /game_sessions/1
  # DELETE /game_sessions/1.json
  def destroy
    @game_session.destroy
    respond_to do |format|
      format.html { redirect_to game_sessions_url, notice: 'Game session was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game_session
      @game_session = GameSession.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_session_params
      params.require(:game_session).permit(:game_id, :finished)
    end
end

app/helpers/game_sessions_helper.rb
module GameSessionsHelper
end

app/views/game_sessions/_form.html.erb
<%= form_for(game_session) do |f| %>
  <% if game_session.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game_session.errors.count, "error") %> prohibited this game_session from being saved:</h2>

      <ul>
      <% game_session.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :game_id %>
    <%= f.number_field :game_id %>
  </div>

  <div class="field">
    <%= f.label :finished %>
    <%= f.check_box :finished %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/game_sessions/edit.html.erb
<h1>Editing Game Session</h1>

<%= render 'form', game_session: @game_session %>

<%= link_to 'Show', @game_session %> |
<%= link_to 'Back', game_sessions_path %>

app/views/game_sessions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Game Sessions</h1>

<table>
  <thead>
    <tr>
      <th>Game</th>
      <th>Player</th>
      <th>Finished</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @game_sessions.each do |game_session| %>
      <tr>
        <td><%= game_session.game_id %></td>
        <td><%= game_session.finished %></td>
        <td><%= link_to 'Show', game_session %></td>
        <td><%= link_to 'Edit', edit_game_session_path(game_session) %></td>
        <td><%= link_to 'Destroy', game_session, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game Session', new_game_session_path %>

app/views/game_sessions/new.html.erb
<h1>New Game Session</h1>

<%= render 'form', game_session: @game_session %>

<%= link_to 'Back', game_sessions_path %>

app/views/game_sessions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Game:</strong>
  <%= @game_session.game_id %>
</p>

<p>
  <strong>Finished:</strong>
  <%= @game_session.finished %>
</p>

<%= link_to 'Edit', edit_game_session_path(@game_session) %> |
<%= link_to 'Back', game_sessions_path %>