config/routes.rb
Rails.application.routes.draw do

  api_version(:module => "V1", :header => {:name => "Accept", :value => "application/vnd.mycompany.com; version=1"}, :parameter => {:name => "version", :value => "1"}, :path => {:value => "v1"}) do
    resources :api, :except => [:show]
  end
  root 'access#index'

  resources :game_session_players
  resources :player_awards
  resources :awards
  resources :player_histories
  resources :game_sessions
  resources :players
  resources :games

  match ':controller(/:action(/:id))', :via => [:get, :post]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/game_session_player.rb
class GameSessionPlayer < ApplicationRecord

  belongs_to :game_session
  belongs_to :player

end

app/controllers/game_session_players_controller.rb
class GameSessionPlayersController < ApplicationController
  before_action :set_game_session_player, only: [:show, :edit, :update, :destroy]

  # GET /game_session_players
  # GET /game_session_players.json
  def index
    @game_session_players = GameSessionPlayer.all
  end

  # GET /game_session_players/1
  # GET /game_session_players/1.json
  def show
  end

  # GET /game_session_players/new
  def new
    @game_session_player = GameSessionPlayer.new
  end

  # GET /game_session_players/1/edit
  def edit
  end

  # POST /game_session_players
  # POST /game_session_players.json
  def create
    @game_session_player = GameSessionPlayer.new(game_session_player_params)

    respond_to do |format|
      if @game_session_player.save
        format.html { redirect_to @game_session_player, notice: 'Game session player was successfully created.' }
        format.json { render :show, status: :created, location: @game_session_player }
      else
        format.html { render :new }
        format.json { render json: @game_session_player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /game_session_players/1
  # PATCH/PUT /game_session_players/1.json
  def update
    respond_to do |format|
      if @game_session_player.update(game_session_player_params)
        format.html { redirect_to @game_session_player, notice: 'Game session player was successfully updated.' }
        format.json { render :show, status: :ok, location: @game_session_player }
      else
        format.html { render :edit }
        format.json { render json: @game_session_player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /game_session_players/1
  # DELETE /game_session_players/1.json
  def destroy
    @game_session_player.destroy
    respond_to do |format|
      format.html { redirect_to game_session_players_url, notice: 'Game session player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game_session_player
      @game_session_player = GameSessionPlayer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_session_player_params
      params.require(:game_session_player).permit(:game_session_id, :player_id, :won)
    end
end

app/helpers/game_session_players_helper.rb
module GameSessionPlayersHelper
end

app/views/game_session_players/_form.html.erb
<%= form_for(game_session_player) do |f| %>
  <% if game_session_player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game_session_player.errors.count, "error") %> prohibited this game_session_player from being saved:</h2>

      <ul>
      <% game_session_player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :game_session_id %>
    <%= f.number_field :game_session_id %>
  </div>

  <div class="field">
    <%= f.label :player_id %>
    <%= f.number_field :player_id %>
  </div>

  <div class="field">
    <%= f.label :won %>
    <%= f.check_box :won %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/game_session_players/edit.html.erb
<h1>Editing Game Session Player</h1>

<%= render 'form', game_session_player: @game_session_player %>

<%= link_to 'Show', @game_session_player %> |
<%= link_to 'Back', game_session_players_path %>

app/views/game_session_players/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Game Session Players</h1>

<table>
  <thead>
    <tr>
      <th>Game session</th>
      <th>Player</th>
      <th>Won</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @game_session_players.each do |game_session_player| %>
      <tr>
        <td><%= game_session_player.game_session_id %></td>
        <td><%= game_session_player.player_id %></td>
        <td><%= game_session_player.won %></td>
        <td><%= link_to 'Show', game_session_player %></td>
        <td><%= link_to 'Edit', edit_game_session_player_path(game_session_player) %></td>
        <td><%= link_to 'Destroy', game_session_player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game Session Player', new_game_session_player_path %>

app/views/game_session_players/new.html.erb
<h1>New Game Session Player</h1>

<%= render 'form', game_session_player: @game_session_player %>

<%= link_to 'Back', game_session_players_path %>

app/views/game_session_players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Game session:</strong>
  <%= @game_session_player.game_session_id %>
</p>

<p>
  <strong>Player:</strong>
  <%= @game_session_player.player_id %>
</p>

<p>
  <strong>Won:</strong>
  <%= @game_session_player.won %>
</p>

<%= link_to 'Edit', edit_game_session_player_path(@game_session_player) %> |
<%= link_to 'Back', game_session_players_path %>